from __future__ import annotations

import copy
import math
import os
import time
import pandas as pd
import torch.nn as nn
import numpy as np
import sys

from sklearn.cluster import AgglomerativeClustering
from abc import ABCMeta
from collections import defaultdict, deque
from river import base, utils
# parallelism
from multiprocessing import Pool, cpu_count

class DenStream(base.Clusterer, nn.Module):

    class BufferItem:
        def __init__(self, x, timestamp, covered):
            self.x         = x
            self.timestamp = (timestamp,)
            self.covered   = covered

    def __init__(
        self,
        mpts                   = [10],
        min_cluster_size       = 10,
        decaying_factor: float = 0.25,
        beta: float            = 0.75,
        mu: float              = 2,
        epsilon: float         = 0.02,
        n_samples_init: int    = 1000,
        stream_speed: int      = 100,
        m_movementThreshold    = 0.5,
        runtime                = False,
        plot                   = False,
        save_partitions        = False,
        percent                = 0.10,
        method_summarization   = 'single_linkage',
        dataset                = ''
    ):
        super().__init__()
        self.percent              = percent
        self.timestamp            = 0
        self.initialized          = False
        self.decaying_factor      = decaying_factor
        self.beta                 = beta
        self.mu                   = mu
        self.epsilon              = epsilon
        self.n_samples_init       = n_samples_init
        self.stream_speed         = stream_speed
        self.mst                  = None
        self.mst_mult             = None
        self.mpts                 = mpts
        self.min_cluster_size     = min_cluster_size
        self.m_movementThreshold  = m_movementThreshold
        self.runtime              = runtime
        self.plot                 = plot
        self.save_partitions      = save_partitions
        self.method_summarization = method_summarization
        self.base_dir_result      = os.path.join("results", dataset)
        self.dataset              = dataset
        
        # number of clusters generated by applying the variant of DBSCAN algorithm
        # on p-micro-cluster centers and their centers
        self.n_clusters = 0
        
        self.clusters: typing.Dict[int, "MicroCluster"]         = {}
        self.p_micro_clusters: typing.Dict[int, "MicroCluster"] = {}
        self.o_micro_clusters: typing.Dict[int, "MicroCluster"] = {}
        
        #mudei o método pq estava dando erro e não estavamos precisando no momento
        self._time_period = math.ceil((1 / self.decaying_factor) * math.log((self.mu * self.beta) / (self.mu * self.beta - 1))) + 1
        
        print("self._time_period", self._time_period)
        self._init_buffer: typing.Deque[typing.Dict] = deque()
        
        self._n_samples_seen = 0
        self.m_update        = None

        self.df_runtime_final = pd.DataFrame(columns=['timestamp', 'micro_clusters', 'summarization', 'total_time'])

        # check that the value of beta is within the range (0,1]
        if not (0 < self.beta <= 1):
            raise ValueError(f"The value of `beta` (currently {self.beta}) must be within the range (0,1].")

    @property
    def centers(self):
        return {k: cluster.getCenter(self.timestamp) for k, cluster in self.clusters.items()}
    
    def distanceEuclidian(self, x1, x2):
        distance = 0
        
        for i in range(len(x1)):
            d         = x1[i] - x2[i]
            distance += d * d
            
        return math.sqrt(distance)

    def _get_closest_cluster_key(self, point, clusters):
        min_distance = math.inf
        key          = -1
        
        for k, cluster in clusters.items():
            distance = self.distanceEuclidian(cluster.getCenter(self.timestamp), point)
            
            if distance < min_distance and distance <= self.epsilon:
                min_distance = distance
                key          = k
                
        return key

    def _merge(self, point):
        # initiate merged status
        merged_status = False
        pos           = self._n_samples_seen - 1

        if self.save_partitions:
            self.df_mc_to_points.loc[pos]          = point
            self.df_mc_to_points.loc[pos, 'id_mc'] = 0

        if len(self.p_micro_clusters) != 0:
            # try to merge p into its nearest p-micro-cluster c_p
            closest_pmc_key = self._get_closest_cluster_key(point, self.p_micro_clusters)
            
            if closest_pmc_key != -1:
                updated_pmc = copy.deepcopy(self.p_micro_clusters[closest_pmc_key])
                updated_pmc.insert(point, self.timestamp)
                
                if updated_pmc.getRadius(self.timestamp) <= self.epsilon:
                    # keep updated p-micro-cluster
                    self.p_micro_clusters[closest_pmc_key] = updated_pmc

                    if self.save_partitions:
                        self.df_mc_to_points.loc[pos, 'id_mc'] = closest_pmc_key

                    merged_status = True

        if not merged_status:
            closest_omc_key = self._get_closest_cluster_key(point, self.o_micro_clusters)
            
            if closest_omc_key != -1:
                updated_omc = copy.deepcopy(self.o_micro_clusters[closest_omc_key])
                updated_omc.insert(point, self.timestamp)

                if updated_omc.getRadius(self.timestamp) <= self.epsilon:
                    # keep updated o-micro-cluster
                    weight_omc = updated_omc.getWeight(self.timestamp)
                    
                    if weight_omc > self.mu * self.beta:
                        # it has grown into a p-micro-cluster
                        del self.o_micro_clusters[closest_omc_key]

                        new_key = 0
                        
                        while new_key in self.p_micro_clusters:
                            new_key += 1
                            
                        updated_omc.setID(new_key)
                        self.p_micro_clusters[new_key] = updated_omc

                        if self.save_partitions:
                            self.df_mc_to_points.loc[pos, 'id_mc'] = new_key
                            self.df_mc_to_points['id_mc']          = self.df_mc_to_points['id_mc'].replace((-1) * closest_omc_key, new_key)
                            
                    else:
                        self.o_micro_clusters[closest_omc_key] = updated_omc

                        # Outliers have our key negative
                        if self.save_partitions:
                            self.df_mc_to_points.loc[pos, 'id_mc'] = (-1) * closest_omc_key
                    
                    merged_status = True
                    
        if not merged_status:
            # create a new o-data_bubble by p and add it to o_data_bubbles
            mc_from_p = MicroCluster(x=point, timestamp=self.timestamp, decaying_factor=self.decaying_factor)

            key_o = 2

            while key_o in self.o_micro_clusters:
                key_o += 1

            self.o_micro_clusters[key_o] = mc_from_p

            if self.save_partitions:
                self.df_mc_to_points.loc[pos, 'id_mc'] = (-1) * key_o

            merged_status = True
    
    @staticmethod
    def _distance(point_a, point_b):
        return utils.math.minkowski_distance(point_a, point_b, 2)

    def _is_directly_density_reachable(self, c_p, c_q, mpts):
        if c_p.calc_weight(self.timestamp) > mpts and c_q.calc_weight(self.timestamp) > mpts:
            # check distance of two clusters and compare with 2*epsilon
            c_p_center = c_p.getCenter(self.timestamp)
            c_q_center = c_q.getCenter(self.timestamp)
            distance = self._distance(c_p_center, c_q_center)
            if distance < 2 * self.epsilon and distance <= c_p.getRadius(self.timestamp) + c_q.getRadius(self.timestamp):
                return True
        return False

    def _query_neighbor(self, cluster, mpts):
        neighbors = deque()
        # scan all clusters within self.p_micro_clusters
        for pmc in self.p_micro_clusters.values():
            # check density reachable and that the cluster itself does not appear in neighbors
            if cluster != pmc and self._is_directly_density_reachable(cluster, pmc, mpts):
                neighbors.append(pmc)
        return neighbors

    @staticmethod
    def _generate_clusters_for_labels(cluster_labels):
        # initiate the dictionary for final clusters
        clusters = {}

        # group clusters per label
        mcs_per_label = defaultdict(deque)
        for mc, label in cluster_labels.items():
            mcs_per_label[label].append(mc)

        # generate set of clusters with the same label
        for label, micro_clusters in mcs_per_label.items():
            # merge clusters with the same label into a big cluster
            cluster = copy.copy(micro_clusters[0])
            for mc in range(1, len(micro_clusters)):
                cluster.merge(micro_clusters[mc])

            clusters[label] = cluster

        return len(clusters), clusters
        
    def _initial_single_linkage(self):
        start = time.time()
        
        self._init_buffer = np.array(self._init_buffer)
        
        # The linkage="single" does a clustering, e. g., the clusters are indentified and form big data bubbles.
        clustering = AgglomerativeClustering(n_clusters = int(self.n_samples_init * self.percent), linkage='average')
        clustering.fit(self._init_buffer)
        
        labels          = clustering.labels_
        labels_visited  = np.zeros(len(labels))
        len_buffer      = len(self._init_buffer)
        count_potential = 0
        min_mc = max_mc = 0
        epsilon         = {}

        if self.save_partitions:
            mc_to_points = []
        
        for i in range(len_buffer):
            label      = labels[i]
            object_new = dict(enumerate(self._init_buffer[i]))
            labels_visited[label] += 1
            
            if labels_visited[label] == 1:
                mc = MicroCluster(
                    x = object_new,
                    timestamp = self.timestamp,
                    decaying_factor = self.decaying_factor,
                )

                mc.setID(label)
                
                self.p_micro_clusters.update({label: mc})
            else:
                self.p_micro_clusters[label].insert(object_new, self.timestamp)

                if labels_visited[label] == self.mu:
                    count_potential += 1
                if self.p_micro_clusters[label].getN() >= self.mu:
                    epsilon[label] = self.p_micro_clusters[label].getRadius(self.timestamp)
                
            max_mc = max(max_mc, self.p_micro_clusters[label].getN())
        
        # outliers data_bubbles
        if count_potential != len(self.p_micro_clusters):
            replace_map = {}
            key         = 0
            key_p       = 0
            key_o       = 2
            
            while labels_visited[key]:
                if labels_visited[key] < self.mu:                    
                    self.o_micro_clusters[key_o] = self.p_micro_clusters[key]
                    self.p_micro_clusters.pop(key)

                    key_o += 1
                else:
                    if key != key_p:
                        self.p_micro_clusters[key].setID(key_p)
                        self.p_micro_clusters[key_p] = self.p_micro_clusters.pop(key)

                        if min_mc == 0:
                            min_mc = self.p_micro_clusters[key_p].getN()
                        else:
                            min_mc = min(min_mc, self.p_micro_clusters[key_p].getN())

                    key_p += 1
                key += 1

        end = time.time()
        
        e_min  = min(epsilon.values())
        e_mean = sum(epsilon.values()) / count_potential
        e_max  = max(epsilon.values())
        
        self.epsilon = e_max
        
        print("> Total: ", (count_potential + len(self.o_micro_clusters)))
        print("> MCs Potential: ", count_potential)
        print("> Min_MC: ", min_mc)
        print("> Max_MC: ", max_mc)
        print("> Time for MCs: ", end - start)
        print("> Epsilon:", self.epsilon)
        
    def time_period_check(self):
        for i, p_micro_cluster_i in list(self.p_micro_clusters.items()):
            if p_micro_cluster_i.getWeight(self.timestamp) < self.mu * self.beta:
                # c_p became an outlier and should be deleted
                del self.p_micro_clusters[i]

        for j, o_micro_cluster_j in list(self.o_micro_clusters.items()):
            # calculate xi
            xi = (2**(-self.decaying_factor * (self.timestamp - o_micro_cluster_j.creation_time + self._time_period)) - 1) / (2 ** (-self.decaying_factor * self._time_period) - 1)                
            if o_micro_cluster_j.getWeight(self.timestamp) < xi:
                # c_o might not grow into a p-micro-cluster, we can safely delete it
                self.o_micro_clusters.pop(j)

    def learn_one(self, x, sample_weight=None):
        self._n_samples_seen += 1
        # control the stream speed
        
        if self._n_samples_seen % self.stream_speed == 0:
            self.timestamp += 1

        # Initialization
        if not self.initialized:
            if self.method_summarization == 'epsilon':
                self._init_buffer.append(self.BufferItem(x, self.timestamp, False))
            else:
                self._init_buffer.append(list(x.values()))
            
            if len(self._init_buffer) == self.n_samples_init:
                print("entrando no initial()")
                if self.method_summarization == 'epsilon':
                    self._initial_epsilon()
                else:
                    self._initial_single_linkage()
                
                self.initialized = True
                del self._init_buffer
                
            return self

        # Merge
        self._merge(x)

        # Periodic cluster removal
        if self.timestamp > 0 and self.timestamp % self._time_period == 0:
            self.time_period_check()

        return self

    def build(self, objects, mptsi):        
        start_total_time = time.time()
        # cluster counter; in this algorithm cluster labels start with 0
        c = -1
        # initiate labels of p-micro-clusters to None
        labels = {pmc: None for pmc in self.p_micro_clusters.values()}

        for pmc in self.p_micro_clusters.values():
            # previously processed in inner loop
            if labels[pmc] is not None:
                continue
            # next cluster label
            c += 1
            labels[pmc] = c
            # neighbors to expand
            seed_queue = self._query_neighbor(pmc, mptsi)
            # process every point in seed set
            while seed_queue:
                # check previously proceeded points
                if labels[seed_queue[0]] is not None:
                    seed_queue.popleft()
                    continue
                if seed_queue:
                    labels[seed_queue[0]] = c
                    # find neighbors of neighbors
                    neighbor_neighbors = self._query_neighbor(seed_queue[0], mptsi)
                    # add new neighbors to seed set
                    for neighbor_neighbor in neighbor_neighbors:
                        if labels[neighbor_neighbor] is not None:
                            seed_queue.append(neighbor_neighbor)

        self.n_clusters, self.clusters = self._generate_clusters_for_labels(labels)

        clusters = []
        for o in objects:
            clusters.append(self._get_closest_cluster_key(o, self.clusters))
        
        end_total_time = time.time()
        
        df_runtime_timestamps = {
            'mpts': mptsi,
            'total': (end_total_time - start_total_time)
        }

        return df_runtime_timestamps

    def predict_one(self, objects, w=None):
        # This function handles the case when a clustering request arrives.
        # implementation of the DBSCAN algorithm proposed by Ester et al.
        if not self.initialized:
            # The model is not ready
            return 0

        self.time_period_check()

        print("MCs-p:", len(self.p_micro_clusters))
        print("MCs-o:", len(self.o_micro_clusters))
        
        start_clustering = time.time()

        # PARALLELISM
        try:
            args = [(objects, mptsi) for mptsi in self.mpts]

            with Pool(processes = (5)) as pool:
                results = pool.starmap(self.build, args)
        except KeyboardInterrupt:
            print("Interrompido pelo usuário")

        end_clustering = time.time()
        print("End_computing")
        
        self.save_runtime_timestamps(results)

        self.df_runtime_final.at[self.timestamp, 'timestamp']      = self.timestamp
        self.df_runtime_final.at[self.timestamp, 'micro_clusters'] = len(self.p_micro_clusters)
        self.df_runtime_final.at[self.timestamp, 'total_time']     = end_clustering - start_clustering

    def save_runtime_final(self):
        m_directory = os.path.join(self.base_dir_result, "runtime")
        
        try:
            if not os.path.exists(m_directory):
                os.makedirs(m_directory)

            with open(os.path.join(m_directory, "runtime_final.csv"), 'w') as writer:
                writer.write("timestamp,micro_clusters,summarization,total_time\n")

                for _, linha in self.df_runtime_final.iterrows():
                    writer.write(str(linha['timestamp']) + ',' + str(linha['micro_clusters']) + ',' + str(linha['summarization']) + ',' + str(linha['total_time']) + "\n")

        except FileNotFoundError as e:
            print(e)

    def save_runtime_timestamps(self, results):
        m_directory = os.path.join(self.base_dir_result, "runtime")
        
        try:
            if not os.path.exists(m_directory):
                os.makedirs(m_directory)

            df_runtime_timestamps = pd.DataFrame(results)

            with open(os.path.join(m_directory, "runtime_t" + str(self.timestamp) + ".csv"), 'w') as writer:
                writer.write("mpts,total\n")
                
                for _, linha in df_runtime_timestamps.iterrows():
                    writer.write(str(linha['mpts']) + ',' + str(linha['total']) + "\n")

        except FileNotFoundError as e:
            print(e)

class MicroCluster(metaclass=ABCMeta):

    s_idCounter = 0
    
    def __init__(self, x, timestamp, decaying_factor):
        self.x               = x
        self.db_id           = MicroCluster.s_idCounter        
        self.last_edit_time  = timestamp
        self.creation_time   = timestamp
        self.decaying_factor = decaying_factor

        self.N              = 1
        self.linear_sum     = x
        self.squared_sum    = {i: (x_val * x_val) for i, x_val in x.items()}        
        self.m_staticCenter = []

    def getID(self):
        return self.db_id

    def setID(self, id):
        self.db_id = id
    
    def calc_cf1(self, fading_function):
        cf1 = []        
        for key in self.linear_sum.keys():
            val_ls = self.linear_sum[key]
            cf1.append(fading_function * val_ls)
        return cf1
    
    def calc_cf2(self, fading_function):
        cf2 = []        
        for key in self.squared_sum.keys():
            val_ss = self.squared_sum[key]
            cf2.append(fading_function * val_ss)
        return cf2

    def calc_weight(self, timestamp):
        return self.getWeight(timestamp)
    
    def getN(self):
        return self.N

    def getWeight(self, timestamp):
        return self.N * self.fading_function(timestamp - self.last_edit_time)
        
    def getCenter(self, timestamp):
        ff     = self.fading_function(timestamp - self.last_edit_time)
        weight = self.getWeight(timestamp)
        center = {key: (ff * val) / weight for key, val in self.linear_sum.items()}
        
        return center

    def getRadius(self, timestamp):        
        ff  = self.fading_function(timestamp - self.last_edit_time)
        w   = self.getWeight(timestamp)        
        cf1 = self.calc_cf1(ff)
        cf2 = self.calc_cf2(ff)        
        res = 0      
        
        for i in range(len(self.linear_sum)):
            x1 = cf2[i] / w
            x2 = math.pow(cf1[i]/w , 2)
            
            tmp = x1 - x2
            
            res += math.sqrt(tmp) if tmp > 0 else (1/10 * 1/10)
            
        #1.8            
        return (res / len(cf1)) * 1.8
        
    def add(self, x):        
        self.N += 1
        
        for key, val in x.items():
            self.linear_sum[key]  += val
            self.squared_sum[key] += val * val
            
    def insert(self, x, timestamp):
        if(self.last_edit_time != timestamp):
            self.fade(timestamp)
        
        self.last_edit_time = timestamp
        
        self.add(x)
    
    def fade(self, timestamp):
        ff = self.fading_function(timestamp - self.last_edit_time)
        
        self.N *= ff
        
        for key, val in self.linear_sum.items():            
            self.linear_sum[key]  *= ff
            self.squared_sum[key] *= ff
        
    def merge(self, cluster):
        self.N += cluster.N
        
        for key in cluster.linear_sum.keys():
            try:
                self.linear_sum[key]  += cluster.linear_sum[key]
                self.squared_sum[key] += cluster.squared_sum[key]
            except KeyError:
                self.linear_sum[key]  = cluster.linear_sum[key]
                self.squared_sum[key] = cluster.squared_sum[key]
                
        if self.last_edit_time < cluster.creation_time:
            self.last_edit_time = cluster.creation_time
            
    def fading_function(self, time):
        return 2 ** (-self.decaying_factor * time)
    
    def setVertexRepresentative(self, v : Vertex): 
        self.m_vertexRepresentative = v

    def getVertexRepresentative(self):
        return self.m_vertexRepresentative
    
    def getStaticCenter(self):
        return self.m_staticCenter

    def setStaticCenter(self, timestamp):
        self.m_staticCenter = self.getCenter(timestamp).copy()
        
    def hasCenterChanged(self,percentage, refEpsilon, timestamp):
        distance = self.getCenterDistance(self.m_staticCenter, timestamp)
        if(distance > percentage * refEpsilon):
            return True
        return False
    def getCenterDistance(self, instance, timestamp):
        distance = 0.0
        center = self.getCenter(timestamp)
        for i in range(len(instance)):
            d = center[i] - instance[i]
            distance += d * d
        return math.sqrt(distance)